services:
  app:
    build:
      context: ../
      dockerfile: deploy/Dockerfile
    volumes:
      - ./config.yml:/srv/config.yml
      - ${SHARE_PATH:?The path where your shared folders are located}:/data
    environment:
      - "FT_URL=${FT_URL:-http://localhost}"
    depends_on:
      - redis
  redis:
    image: redis:alpine
  nginx:
    image: nginx:alpine
    ports:
      - "${HTTP_PORT:-80}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ${SHARE_PATH:?The path where your shared folders are located}:/data
    depends_on:
      - app
